// Command txtgen converts SMF language files (PHP, e.g.
// Themes/default/languages/index.english.php) into Go data for
// internal/lang. It parses the constrained PHP subset those files use:
//
//	$txt['key'] = 'literal';            (single or double quoted)
//	$txt[123] = 'literal';
//	$txt['days'] = array('a', 'b');     (optionally 1 => 'a', ...)
//	$txt[18] = $context['forum_name'] . ' - Index';   (concatenations)
//
// Concatenated variables become {placeholder} markers (see internal/lang).
// Any construct it cannot translate is a fatal error, so new language files
// get hand-audited instead of silently mis-generated.
//
//	Usage: go run ./tools/txtgen -langdir ../Themes/default/languages \
//		-language english -out internal/lang/english_gen.go index Errors ...
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func main() {
	langdir := flag.String("langdir", "", "directory with *.english.php files")
	language := flag.String("language", "english", "language name in filenames")
	out := flag.String("out", "", "output .go file")
	flag.Parse()
	files := flag.Args()
	if *langdir == "" || *out == "" || len(files) == 0 {
		log.Fatal("usage: txtgen -langdir DIR -out FILE.go name [name...]")
	}

	var b strings.Builder
	b.WriteString("// Code generated by tools/txtgen; DO NOT EDIT.\n\npackage lang\n\n")
	varNames := make(map[string]string)
	for _, name := range files {
		path := filepath.Join(*langdir, name+"."+*language+".php")
		src, err := os.ReadFile(path)
		if err != nil {
			log.Fatal(err)
		}
		f, err := parseFile(string(src))
		if err != nil {
			log.Fatalf("%s: %v", path, err)
		}
		varName := strings.Title(*language) + sanitize(name)
		varNames[name] = varName
		writeFile(&b, varName, f)
	}

	b.WriteString(fmt.Sprintf("var %s = map[string]*File{\n", strings.Title(*language)))
	names := append([]string{}, files...)
	sort.Strings(names)
	for _, name := range names {
		b.WriteString(fmt.Sprintf("\t%q: %s,\n", name, varNames[name]))
	}
	b.WriteString("}\n")

	if err := os.WriteFile(*out, []byte(b.String()), 0644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("wrote %s (%d files)\n", *out, len(files))
}

func sanitize(s string) string {
	return strings.NewReplacer("-", "", ".", "").Replace(strings.Title(s))
}

type parsedFile struct {
	order       []string // keys in source order, for stable output
	strings     map[string]string
	dynamic     map[string]string
	helpStrings map[string]string // $helptxt literals
	helpDynamic map[string]string // $helptxt non-literals
	lists       map[string]parsedList
}

type parsedList struct {
	base  int
	items []string
}

// Hand-audited overrides for entries txtgen cannot translate mechanically.
// Split by namespace ($txt vs $helptxt): several keys exist in both arrays with
// different values, so an override must only apply to the array it belongs to.
var overridesTxt = map[string]string{
	// (empty($modSettings['password_strength']) ? 4 : 8)
	"profile_error_password_short": "Your password must be at least {password_min_chars} characters long.",
	// ModSettings description with the theme-settings link interpolated.
	"smf3": `This page allows you to change the settings of features, mods, and basic options in your forum.  Please see the <a href="{scripturl}?action=theme;sa=settings;th={theme_id};sesc={session_id}">theme settings</a> for more options.  Click the help icons for more information about a setting.`,
}
var overridesHelp = map[string]string{
	// function_exists('pspell_new') ? 'DOES' : 'DOES NOT' — this port has no
	// pspell, so the result is always 'DOES NOT'.
	"enableSpellChecking": "Enable spell checking. You MUST have the pspell library installed on your server and your PHP configuration set up to use the pspell library. Your server DOES NOT appear to have this set up.",
	// strpos(php_sapi_name(), 'apache') — this port doesn't run under Apache,
	// so the queryless-URL rewrite "will not work on your server".
	"queryless_urls": "This changes the format of URLs a little so search engines will like them better.  They will look like index.php/topic,1.html.<br /><br />This feature will not work on your server.",
}

func parseFile(src string) (*parsedFile, error) {
	f := &parsedFile{
		strings:     map[string]string{},
		dynamic:     map[string]string{},
		helpStrings: map[string]string{},
		helpDynamic: map[string]string{},
		lists:       map[string]parsedList{},
	}
	lines := strings.Split(src, "\n")
	for i := 0; i < len(lines); i++ {
		line := strings.TrimSpace(lines[i])
		if line == "" || strings.HasPrefix(line, "//") || strings.HasPrefix(line, "<?") ||
			strings.HasPrefix(line, "?>") || strings.HasPrefix(line, "global ") ||
			strings.HasPrefix(line, "/*") || strings.HasPrefix(line, "*") {
			continue
		}
		if !strings.HasPrefix(line, "$txt[") && !strings.HasPrefix(line, "$helptxt[") {
			continue
		}
		isHelp := strings.HasPrefix(line, "$helptxt[")
		// Pick the destination maps + override set for this namespace.
		strMap, dynMap, ovr := f.strings, f.dynamic, overridesTxt
		if isHelp {
			strMap, dynMap, ovr = f.helpStrings, f.helpDynamic, overridesHelp
		}
		// Accumulate until the statement's terminating ';' (some entries span lines).
		for !statementComplete(line) && i+1 < len(lines) {
			i++
			line += "\n" + strings.TrimRight(lines[i], "\r")
		}
		key, expr, err := splitAssignment(line)
		if err != nil {
			return nil, err
		}
		if tpl, ok := ovr[key]; ok {
			dynMap[key] = tpl
			f.order = append(f.order, key)
			continue
		}
		if strings.HasPrefix(expr, "array(") {
			base, items, err := parseArray(expr)
			if err != nil {
				return nil, fmt.Errorf("key %s: %w", key, err)
			}
			f.lists[key] = parsedList{base, items}
			f.order = append(f.order, key)
			continue
		}
		val, dynamic, err := parseConcat(expr)
		if err != nil {
			return nil, fmt.Errorf("key %s: %w", key, err)
		}
		if dynamic {
			dynMap[key] = val
		} else {
			strMap[key] = val
		}
		f.order = append(f.order, key)
	}
	return f, nil
}

// statementComplete reports whether the line ends a PHP statement (';' at
// end, outside any string literal).
func statementComplete(line string) bool {
	inStr := byte(0)
	for i := 0; i < len(line); i++ {
		c := line[i]
		if inStr != 0 {
			if c == '\\' {
				i++
			} else if c == inStr {
				inStr = 0
			}
			continue
		}
		if c == '\'' || c == '"' {
			inStr = c
		}
	}
	return inStr == 0 && strings.HasSuffix(strings.TrimSpace(line), ";")
}

// splitAssignment splits `$txt['key'] = EXPR;` into key and EXPR.
func splitAssignment(line string) (string, string, error) {
	open := strings.IndexByte(line, '[')
	close_ := strings.IndexByte(line, ']')
	if open < 0 || close_ < open {
		return "", "", fmt.Errorf("bad assignment: %s", line)
	}
	key := strings.Trim(line[open+1:close_], "'\"")
	rest := strings.TrimSpace(line[close_+1:])
	if strings.HasPrefix(rest, ".=") {
		return "", "", fmt.Errorf("unsupported .= for key %s", key)
	}
	if !strings.HasPrefix(rest, "=") {
		return "", "", fmt.Errorf("expected = for key %s", key)
	}
	expr := strings.TrimSpace(rest[1:])
	expr = strings.TrimSuffix(strings.TrimSpace(expr), ";")
	return key, strings.TrimSpace(expr), nil
}

// parseArray parses array('a', 'b') or array(1 => 'a', 'b').
func parseArray(expr string) (int, []string, error) {
	inner := strings.TrimSuffix(strings.TrimPrefix(expr, "array("), ")")
	base := 0
	if arrow := strings.Index(inner, "=>"); arrow >= 0 && arrow < strings.IndexAny(inner, "'\"") {
		n, err := strconv.Atoi(strings.TrimSpace(inner[:arrow]))
		if err != nil {
			return 0, nil, fmt.Errorf("bad array base in %s", expr)
		}
		base = n
		inner = inner[arrow+2:]
	}
	var items []string
	rest := strings.TrimSpace(inner)
	for rest != "" {
		s, remaining, err := parseQuoted(rest)
		if err != nil {
			return 0, nil, err
		}
		items = append(items, s)
		rest = strings.TrimSpace(remaining)
		rest = strings.TrimPrefix(rest, ",")
		rest = strings.TrimSpace(rest)
	}
	return base, items, nil
}

// parseConcat parses a '.'-joined chain of string literals and known
// variables. Returns the resulting template and whether any placeholder
// (dynamic part) was used.
func parseConcat(expr string) (string, bool, error) {
	var b strings.Builder
	dynamic := false
	rest := strings.TrimSpace(expr)

	// Special-case booleans (lang_rtl): false -> "", true -> "1".
	if rest == "false" {
		return "", false, nil
	}
	if rest == "true" {
		return "1", false, nil
	}

	for rest != "" {
		switch {
		case rest[0] == '\'' || rest[0] == '"':
			s, remaining, err := parseQuoted(rest)
			if err != nil {
				return "", false, err
			}
			b.WriteString(s)
			rest = remaining
		case strings.HasPrefix(rest, "$scripturl"):
			b.WriteString("{scripturl}")
			dynamic = true
			rest = rest[len("$scripturl"):]
		case strings.HasPrefix(rest, "$boardurl"):
			b.WriteString("{boardurl}")
			dynamic = true
			rest = rest[len("$boardurl"):]
		case strings.HasPrefix(rest, "$forum_version"):
			b.WriteString("{forum_version}")
			dynamic = true
			rest = rest[len("$forum_version"):]
		case strings.HasPrefix(rest, "$forum_copyright"):
			b.WriteString("{forum_copyright}")
			dynamic = true
			rest = rest[len("$forum_copyright"):]
		case strings.HasPrefix(rest, "$webmaster_email"):
			b.WriteString("{webmaster_email}")
			dynamic = true
			rest = rest[len("$webmaster_email"):]
		case strings.HasPrefix(rest, "$context['forum_name']"):
			b.WriteString("{forum_name}")
			dynamic = true
			rest = rest[len("$context['forum_name']"):]
		case strings.HasPrefix(rest, "(isset($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : 'unknown')"):
			b.WriteString("{http_referer}")
			dynamic = true
			rest = rest[len("(isset($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : 'unknown')"):]
		case strings.HasPrefix(rest, "$_SERVER['HTTP_USER_AGENT']"):
			b.WriteString("{http_user_agent}")
			dynamic = true
			rest = rest[len("$_SERVER['HTTP_USER_AGENT']"):]
		case strings.HasPrefix(rest, "$GLOBALS['user_info']['ip']"):
			b.WriteString("{user_ip}")
			dynamic = true
			rest = rest[len("$GLOBALS['user_info']['ip']"):]
		case strings.HasPrefix(rest, "$settings['images_url']"):
			b.WriteString("{images_url}")
			dynamic = true
			rest = rest[len("$settings['images_url']"):]
		case strings.HasPrefix(rest, "$modSettings["):
			end := strings.IndexByte(rest, ']')
			key := strings.Trim(rest[len("$modSettings["):end], "'\"")
			b.WriteString("{modSettings:" + key + "}")
			dynamic = true
			rest = rest[end+1:]
		case strings.HasPrefix(rest, "$txt["):
			end := strings.IndexByte(rest, ']')
			key := strings.Trim(rest[len("$txt["):end], "'\"")
			b.WriteString("{txt:" + key + "}")
			dynamic = true
			rest = rest[end+1:]
		default:
			return "", false, fmt.Errorf("untranslatable expression: %s", rest)
		}
		rest = strings.TrimSpace(rest)
		if rest == "" {
			break
		}
		if rest[0] != '.' {
			return "", false, fmt.Errorf("expected '.' in: %s", rest)
		}
		rest = strings.TrimSpace(rest[1:])
	}
	return b.String(), dynamic, nil
}

// parseQuoted reads a PHP string literal from the start of s, returning the
// decoded value and the remaining input.
func parseQuoted(s string) (string, string, error) {
	if s == "" || (s[0] != '\'' && s[0] != '"') {
		return "", "", fmt.Errorf("expected string literal at: %.40s", s)
	}
	q := s[0]
	var b strings.Builder
	for i := 1; i < len(s); i++ {
		c := s[i]
		if c == '\\' && i+1 < len(s) {
			n := s[i+1]
			if q == '\'' {
				// Single-quoted: only \' and \\ are escapes.
				if n == '\'' || n == '\\' {
					b.WriteByte(n)
					i++
				} else {
					b.WriteByte(c)
				}
			} else {
				switch n {
				case 'n':
					b.WriteByte('\n')
				case 't':
					b.WriteByte('\t')
				case 'r':
					b.WriteByte('\r')
				case '"', '\\', '$':
					b.WriteByte(n)
				default:
					b.WriteByte(c)
					b.WriteByte(n)
				}
				i++
			}
			continue
		}
		if c == q {
			return b.String(), s[i+1:], nil
		}
		b.WriteByte(c)
	}
	return "", "", fmt.Errorf("unterminated string: %.40s", s)
}

func writeFile(b *strings.Builder, varName string, f *parsedFile) {
	// order may list a key twice (present in both $txt and $helptxt); emit each
	// (key, map) pair at most once to avoid duplicate Go map literals.
	emitMap := func(label string, m map[string]string) {
		fmt.Fprintf(b, "\t%s: map[string]string{\n", label)
		seen := map[string]bool{}
		for _, k := range f.order {
			if seen[k] {
				continue
			}
			if v, ok := m[k]; ok {
				seen[k] = true
				fmt.Fprintf(b, "\t\t%q: %q,\n", k, v)
			}
		}
		b.WriteString("\t},\n")
	}
	fmt.Fprintf(b, "var %s = &File{\n", varName)
	emitMap("Strings", f.strings)
	emitMap("Dynamic", f.dynamic)
	b.WriteString("\tLists: map[string]List{\n")
	seenList := map[string]bool{}
	for _, k := range f.order {
		if seenList[k] {
			continue
		}
		if v, ok := f.lists[k]; ok {
			seenList[k] = true
			fmt.Fprintf(b, "\t\t%q: {Base: %d, Items: %#v},\n", k, v.base, v.items)
		}
	}
	b.WriteString("\t},\n")
	emitMap("HelpStrings", f.helpStrings)
	emitMap("HelpDynamic", f.helpDynamic)
	b.WriteString("}\n\n")
}
