########## Maintenance ##########
# Set to 1 to enable Maintenance Mode, 2 to make the forum untouchable.
maintenance = 0
mtitle = Maintenance Mode
mmessage = Okay faithful users...we're attempting to restore an older backup of the database...news will be posted once we're back!

########## Forum Info ##########
mbname = My Community
language = english
# URL to your forum, without the trailing /!
boardurl = http://127.0.0.1:8080
webmaster_email = noreply@myserver.com
cookiename = SMFCookie11

########## Database ##########
db_path = ./smf.sqlite
db_prefix = smf_

########## Server ##########
listen = :8080
# Directory containing Themes/, Smileys/, avatars/ and the attachments dir.
assetdir = .
