package app

// Runtime for $txt: mirrors loadLanguage() from Load.php. Controllers load
// language files by name; later loads override earlier ones (PHP include
// order). Data comes from internal/lang (generated by tools/txtgen).
//
// Dynamic entries carry {placeholder} markers resolved per request here.

import (
	"strings"

	"smf/internal/lang"
)

const forumVersion = "SMF 1.1.21"

// loadLanguage merges the named language file into this request's $txt.
func (c *Ctx) loadLanguage(name string) {
	f, ok := lang.English[name]
	if !ok {
		// Mirrors loadLanguage's $fatal=false path: log and continue. The
		// generated set grows as phases port more files; a missing file here
		// during development is loud in the error log.
		c.logError("loadLanguage: no generated language file " + name)
		return
	}
	for _, g := range c.langFiles {
		if g == f {
			return
		}
	}
	c.langFiles = append(c.langFiles, f)
}

// Txt is $txt[key]. Returns "" for unknown keys (PHP would notice-and-empty).
func (c *Ctx) Txt(key string) string {
	for i := len(c.langFiles) - 1; i >= 0; i-- {
		f := c.langFiles[i]
		if v, ok := f.Strings[key]; ok {
			return v
		}
		if tpl, ok := f.Dynamic[key]; ok {
			return c.resolveTxt(tpl)
		}
	}
	return ""
}

// HelpTxt is $helptxt[key], the help-popup descriptions. SMF keeps these in a
// separate array from $txt; many keys exist in both with different text.
func (c *Ctx) HelpTxt(key string) string {
	for i := len(c.langFiles) - 1; i >= 0; i-- {
		f := c.langFiles[i]
		if v, ok := f.HelpStrings[key]; ok {
			return v
		}
		if tpl, ok := f.HelpDynamic[key]; ok {
			return c.resolveTxt(tpl)
		}
	}
	return ""
}

// HelpTxtHas reports whether $helptxt[key] exists.
func (c *Ctx) HelpTxtHas(key string) bool {
	for i := len(c.langFiles) - 1; i >= 0; i-- {
		f := c.langFiles[i]
		if _, ok := f.HelpStrings[key]; ok {
			return true
		}
		if _, ok := f.HelpDynamic[key]; ok {
			return true
		}
	}
	return false
}

// TxtHas reports whether the key exists, as isset($txt[key]).
func (c *Ctx) TxtHas(key string) bool {
	for i := len(c.langFiles) - 1; i >= 0; i-- {
		f := c.langFiles[i]
		if _, ok := f.Strings[key]; ok {
			return true
		}
		if _, ok := f.Dynamic[key]; ok {
			return true
		}
	}
	return false
}

// TxtList is $txt[key] for array entries (days, months...). The returned
// accessor maps PHP indexes (respecting the array's base) to items.
func (c *Ctx) TxtList(key string) lang.List {
	for i := len(c.langFiles) - 1; i >= 0; i-- {
		if l, ok := c.langFiles[i].Lists[key]; ok {
			return l
		}
	}
	return lang.List{}
}

// TxtListItem returns $txt[key][index] with the list's base applied.
func (c *Ctx) TxtListItem(key string, index int) string {
	l := c.TxtList(key)
	i := index - l.Base
	if i < 0 || i >= len(l.Items) {
		return ""
	}
	return l.Items[i]
}

// resolveTxt substitutes {placeholder} markers in dynamic entries.
func (c *Ctx) resolveTxt(tpl string) string {
	var b strings.Builder
	for {
		open := strings.IndexByte(tpl, '{')
		if open < 0 {
			b.WriteString(tpl)
			break
		}
		close_ := strings.IndexByte(tpl[open:], '}')
		if close_ < 0 {
			b.WriteString(tpl)
			break
		}
		b.WriteString(tpl[:open])
		marker := tpl[open+1 : open+close_]
		tpl = tpl[open+close_+1:]

		switch {
		case marker == "forum_name":
			b.WriteString(c.App.Config.MbName)
		case marker == "scripturl":
			b.WriteString(c.App.ScriptURL)
		case marker == "boardurl":
			b.WriteString(c.App.Config.BoardURL)
		case marker == "forum_version":
			b.WriteString(forumVersion)
		case marker == "http_referer":
			if ref := c.R.Header.Get("Referer"); ref != "" {
				b.WriteString(ref)
			} else {
				b.WriteString("unknown")
			}
		case marker == "http_user_agent":
			b.WriteString(c.UserAgent)
		case marker == "user_ip":
			b.WriteString(c.User.IP)
		case marker == "images_url":
			b.WriteString(c.Theme.ImagesURL())
		case marker == "session_id":
			b.WriteString(c.Sc)
		case marker == "theme_id":
			b.WriteString(itoa(c.Theme.Int("theme_id")))
		case marker == "webmaster_email":
			b.WriteString(c.App.Config.WebmasterEmail)
		case marker == "forum_copyright":
			b.WriteString(c.forumCopyright())
		case marker == "password_min_chars":
			// (empty($modSettings['password_strength']) ? 4 : 8)
			if c.App.SettingEmpty("password_strength") {
				b.WriteString("4")
			} else {
				b.WriteString("8")
			}
		case strings.HasPrefix(marker, "modSettings:"):
			b.WriteString(c.App.Setting(marker[len("modSettings:"):]))
		case strings.HasPrefix(marker, "txt:"):
			b.WriteString(c.Txt(marker[len("txt:"):]))
		default:
			// Unknown marker: emit verbatim so it is visible in goldens.
			b.WriteString("{" + marker + "}")
		}
	}
	return b.String()
}

// forumCopyright is $forum_copyright from index.english.php (a top-level
// variable, not a $txt entry, so it lives here rather than in the generated
// data). The literal newline matters for byte-identical footers.
func (c *Ctx) forumCopyright() string {
	return `<a href="http://www.simplemachines.org/" title="Simple Machines Forum" target="_blank">Powered by smf-go</a> |
<a href="http://www.simplemachines.org/about/copyright.php" title="Free Forum Software" target="_blank">SMF &copy; 2015, Simple Machines</a>`
}
